yolapi/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

from pypi.views import index
from sync.views import sync

urlpatterns = [
    path('', index, name='index'),
    path('pypi/', include(('pypi.urls', 'pypi'), namespace='pypi')),
    path(
        'simple/',
        include(('pypi.simple.urls', 'pypi'), namespace='simple')
    ),

    path(
        'importer/',
        include(('importer.urls', 'importer'), namespace='importer')
    ),
    path('sync/', sync, name='sync'),

    path(
        'robots.txt',
        TemplateView.as_view(
            template_name='robots.txt', content_type='text/plain'
        )
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yolapi/pypi/simple/urls.py
from django.urls import path, re_path

from pypi.simple import views as simple_views

urlpatterns = [
    path('', simple_views.index, name='index'),
    re_path(
        r'^(?P<package>[\w_.\-]+)/$', simple_views.package, name='package'),
    re_path(r'^(?P<package>[\w_.\-]+)/(?P<version>[\w_.\-]+)/$',
        simple_views.release, name='release'),
]

yolapi/pypi/urls.py
from django.urls import path, re_path

from pypi import views as pypi_views

urlpatterns = [
    path('', pypi_views.index, name='index'),
    re_path(r'^(?P<package>[\w_.\-]+)/$', pypi_views.package, name='package'),
    re_path(r'^(?P<package>[\w_.\-]+)/(?P<version>[\w_.\-+]+)/$',
        pypi_views.release, name='release'),
    re_path(r'^(?P<package>[\w_.\-]+)/(?P<version>[\w_.\-+]+)'
        r'/(?P<filetype>[\w_]+)/$', pypi_views.delete, name='delete'),
    re_path(r'^(?P<package>[\w_.\-]+)/(?P<version>[\w_.\-+]+)'
        r'/(?P<filetype>[\w_]+)/(?P<pyversion>[\d.]+|any)/$',
        pypi_views.delete, name='delete'),
]

yolapi/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.generic.simple import direct_to_template


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'yolapi.pypi.views.index', name='index'),
    url(r'^pypi/', include('yolapi.pypi.urls')),
    url(r'^simple/', include('yolapi.pypi.simple.urls')),

    url(r'^importer/', include('yolapi.importer.urls')),
    url(r'^sync/$', 'yolapi.sync.views.sync'),

    url(r'^robots.txt$', direct_to_template,
        {'template': 'robots.txt', 'mimetype': 'text/plain'}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

yolapi/pypi/models.py
import errno
import json
import logging
import os
import re

from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils import timezone
from django.utils.functional import cached_property
from packaging_legacy.version import parse as parse_version

from pypi.fields import CanonicalizedPackageNameField

log = logging.getLogger(__name__)


class PyPIStorage(FileSystemStorage):
    """A Storage system that archives deleted files out of the way, allowing
    new files to always have their expected filenames.
    Almost certainly a little racy"""

    def save(self, name, content, max_length=None):
        if self.exists(name):
            self._archive(name, unexpected=True)
        return super(PyPIStorage, self).save(name, content, max_length)

    def delete(self, name):
        if self.exists(name):
            self._archive(name)
        super(PyPIStorage, self).delete(name)

    def get_valid_name(self, name):
        # Like django.utils.get_valid_name, but allowing + too
        name = str(name).strip().replace(' ', '_')
        return re.sub(r'(?u)[^-\w.+]', '', name)

    def get_available_name(self, name, max_length=None):
        return name

    def _archive(self, name, unexpected=False):
        if unexpected:
            log.warn('Unexpectedly overwriting a file: %s', name)

        archive_replaced = getattr(settings, 'PYPI_ARCHIVE', 'archive')
        if archive_replaced:
            try:
                os.mkdir(self.path(archive_replaced))
            except OSError as e:
                if e.errno != errno.EEXIST:
                    raise

            created = self.get_created_time(name)
            new_name = '%s/%s-%s' % (archive_replaced,
                                     created.strftime('%Y%m%dT%H%M%SZ'),
                                     os.path.basename(name))
            log.info('Archiving %s -> %s', name, new_name)
            os.rename(self.path(name), self.path(new_name))


class Package(models.Model):
    name = CanonicalizedPackageNameField(max_length=255, unique=True,
                                         primary_key=True, editable=False)

    @property
    def sorted_releases_desc(self):
        return sorted(
            self.releases.iterator(),
            key=lambda r: parse_version(r.version),
            reverse=True
        )

    @property
    def latest(self):
        return self.sorted_releases_desc[0]

    def gc(self):
        if not self.releases.exists():
            self.delete()

    def __str__(self):
        return self.name


class Release(models.Model):
    package = models.ForeignKey(
        Package, related_name='releases', on_delete=models.CASCADE)
    version = models.CharField(max_length=128, db_index=True, editable=False)
    metadata = models.TextField()

    class Meta(object):
        unique_together = (('package', 'version'),)

    @property
    def distribution(self):
        """Return the source upload if possible, otherwise the first upload"""
        try:
            return self.distributions.filter(filetype='sdist')[0]
        except IndexError:
            pass

        try:
            return self.distributions.all()[0]
        except IndexError:
            return None

    @cached_property
    def metadata_dict(self):
        try:
            return json.loads(self.metadata)
        except ValueError:
            return {}

    @property
    def metadata_version(self):
        return self.metadata_dict.get('Metadata-Version')

    @property
    def requires_python(self):
        return self.metadata_dict.get('Requires-Python')

    @property
    def summary(self):
        return self.metadata_dict.get('Summary')

    def gc(self):
        if not self.distributions.exists():
            self.delete()

    def __str__(self):
        return f'{self.package.name} {self.version}'


class Distribution(models.Model):
    release = models.ForeignKey(
        Release, related_name='distributions', on_delete=models.CASCADE)
    content = models.FileField(storage=PyPIStorage(),
            upload_to=getattr(settings, 'PYPI_DISTS', 'dists'), blank=False)
    md5_digest = models.CharField(max_length=32, blank=False, editable=False)
    filetype = models.CharField(max_length=32, blank=False, editable=False)
    pyversion = models.CharField(max_length=16, blank=True, editable=False)
    created = models.DateTimeField(default=timezone.now, editable=False)

    class Meta(object):
        unique_together = (('release', 'filetype', 'pyversion'),)

    def __init__(self, *args, **kwargs):
        self.sync_imported = kwargs.pop('sync_imported', False)
        super(Distribution, self).__init__(*args, **kwargs)

    @property
    def path(self):
        return self.content.name

    @property
    def filename(self):
        return os.path.basename(self.path)

    def __str__(self):
        return self.filename

    def delete(self, *args, **kwargs):
        """Delete files off disk (not transaction-safe)"""
        self.content.delete()
        super(Distribution, self).delete(*args, **kwargs)
    delete.alters_data = True


@receiver(post_delete, sender=Distribution)
def gc_releases(sender, **kwargs):
    kwargs['instance'].release.gc()


@receiver(post_delete, sender=Release)
def gc_packages(sender, **kwargs):
    kwargs['instance'].package.gc()

yolapi/pypi/simple/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.decorators.http import require_safe

from pypi.models import Package, Release


@require_safe
def index(request):
    return render(request, 'pypi.simple/index.html', {
        'title': 'Packages',
        'packages': Package.objects.iterator(),
    })


@require_safe
def package(request, package):
    try:
        package = Package.objects.get(name=package)
    except Package.DoesNotExist:
        raise Http404
    return render(request, 'pypi.simple/package.html', {
        'title': str(package),
        'package': package,
    })


@require_safe
def release(request, package, version):
    try:
        release = Release.objects.get(package__name=package, version=version)
    except Release.DoesNotExist:
        raise Http404
    return render(request, 'pypi.simple/release.html', {
        'title': str(release),
        'release': release,
    })

yolapi/pypi/views.py
import logging

from django.conf import settings
from django.http import (
    Http404,
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseForbidden,
)
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
from django.views.decorators.http import (
    require_POST,
    require_http_methods,
    require_safe,
)

import pypi.upload
from pypi.metadata import display_sort, render_description
from pypi.models import Distribution, Package, Release

log = logging.getLogger(__name__)


@require_http_methods(['HEAD', 'GET', 'POST'])
@csrf_exempt
@ensure_csrf_cookie
def index(request):
    if request.method == 'POST':
        return upload(request)
    return render(request, 'pypi/index.html', {
        'title': 'Package list',
        'packages': Package.objects.order_by('name').iterator(),
    })


@require_POST
@csrf_exempt
def upload(request):
    if not settings.DEBUG or 'REMOTE_USER' in request.META:
        allowed_uploaders = getattr(settings, 'PYPI_ALLOWED_UPLOADERS', [])
        if request.META.get('REMOTE_USER') not in allowed_uploaders:
            return HttpResponseForbidden('You are not an authorized uploader',
                                         content_type='text/plain')
    try:
        pypi.upload.process(request)
    except pypi.upload.InvalidUpload as e:
        return HttpResponseBadRequest(str(e), content_type='text/plain')
    except pypi.upload.ReplacementDenied as e:
        return HttpResponseForbidden(str(e), content_type='text/plain')
    return HttpResponse('Accepted, thank you', content_type='text/plain')


@require_safe
@ensure_csrf_cookie
def package(request, package):
    try:
        package = Package.objects.get(name=package)
    except Package.DoesNotExist:
        raise Http404
    return render(request, 'pypi/package.html', {
        'title': str(package),
        'package': package,
    })


@require_safe
@ensure_csrf_cookie
def release(request, package, version):
    try:
        release = Release.objects.get(package__name=package, version=version)
    except Release.DoesNotExist:
        raise Http404

    metadata = release.metadata_dict

    # Flatten lists
    for key, values in metadata.items():
        if isinstance(values, list):
            metadata[key] = '\n'.join(values)

    if 'Description' in metadata:
        content_type = metadata.get('Description-Content-Type', 'text/x-rst')
        content_type = content_type.split(';', 1)[0]
        metadata['Description'] = render_description(
            metadata['Description'], content_type)

    return render(request, 'pypi/release.html', {
        'title': str(release),
        'release': release,
        'metadata': display_sort(metadata),
    })


@require_http_methods(['DELETE'])
def delete(request, package, version, filetype, pyversion=''):
    if not getattr(settings, 'PYPI_ALLOW_DELETION'):
        return HttpResponseForbidden('Deletion is not allowed')

    try:
        distribution = Distribution.objects.get(release__package__name=package,
                                                release__version=version,
                                                filetype=filetype,
                                                pyversion=pyversion)
    except Distribution.DoesNotExist:
        raise Http404

    distribution.delete()

    return HttpResponse('Distribution deleted.', content_type='text/plain')

yolapi/pypi/templates/pypi/index.html
{% extends "base.html" %}
{% load static %}

{% block nav %}
<li><a href="{% url 'pypi:index' %}" class="active">Packages</a></li>
{% endblock %}

{% block content %}
<table id="packages" class="table table-striped sortable">
    <thead>
        <tr>
            <th>Package</th>
            <th>Latest Version</th>
            <th>Uploaded</th>
            <th>Description</th>
        </tr>
    </thead>
{% for package in packages %}
    {% with latest_release=package.latest %}
        <tr>
            <td><a href="{% url 'pypi:package' package=package.name %}">
                {{ package.name }}
            </a></td>
            <td><a href="{% url 'pypi:release' package=package.name version=latest_release.version %}">
                {{ latest_release.version }}
            </a></td>
            <td>{{ latest_release.distribution.created|date:"SHORT_DATE_FORMAT" }}</td>
            <td>{{ latest_release.summary }}</td>
        </tr>
    {% endwith %}
{% endfor %}
</table>
<script src="{% static 'js/sorttable.js' %}"></script>
{% endblock %}

yolapi/pypi/templates/pypi/package.html
{% extends "base.html" %}

{% block nav %}
<li><a href="{% url 'pypi:index' %}">Packages</a></li>
<li><a href="#" class="active">{{ package.name }}</a></li>
{% endblock %}

{% block content %}
<table class="table table-striped">
	<thead>
		<tr>
			<th>Version</th>
			<th>Uploaded</th>
		</tr>
	</thead>
{% for release in package.sorted_releases_desc %}
	<tr>
		<td>
			<a href="{% url 'pypi:release' package=package.name version=release.version %}">
				{{ release.version }}
			</a>
		</td>
		<td>{{ release.distribution.created }}</td>
	</tr>
{% endfor %}
</table>
{% endblock %}

yolapi/pypi/templates/pypi/release.html
{% extends "base.html" %}

{% block nav %}
<li><a href="{% url 'pypi:index' %}">Packages</a></li>
<li><a href="{% url 'pypi:package' package=release.package %}">{{ release.package.name }}</a></li>
<li><a href="#" class="active">{{ release.version }}</a></li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="span4">
        <h2>Files</h2>
        <ul>
        {% for distribution in release.distributions.iterator %}
            <li>
                <a href="{{ distribution.content.url }}#md5={{ distribution.md5_digest }}">
                    {{ distribution.filename }}
                </a>
                <a class="delete"
                {% if distribution.pyversion %}
                   data-url="{% url 'pypi:delete' package=release.package.name version=release.version filetype=distribution.filetype pyversion=distribution.pyversion %}"
                {% else %}
                   data-url="{% url 'pypi:delete' package=release.package.name version=release.version filetype=distribution.filetype %}"
                {% endif %}
                   data-package="{{ release.package.name }}"
                   data-version="{{ release.version }}"
                   data-filetype="{{ distribution.filetype }}"
                   data-pyversion="{{ distribution.pyversion }}"
                   href="#">
                   <i class="icon-remove"></i>
                </a>
            </li>
        {% endfor %}
        </ul>
    </div>
    <div class="span8">
        <h2>Metadata</h2>
        <table class="table table-striped">
        {% for k, v in metadata %}
            <tr>
                <th>{{ k }}</th>
                <td>
                    {% if k == 'Description' %}
                        {{ v }}
                    {% else %}
                        {{ v|urlize|linebreaks }}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </table>
    </div>
    <div class="modal hide fade" id='confirm-deletion'>
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Confirm deletion</h3>
        </div>
        <div class="modal-body">
            <p>Are you sure that you want to delete:</p>
            <dl>
                <dt>Package:</dt>
                <dd class="package"></dd>
                <dt>Version:</dt>
                <dd class="version"></dd>
                <dt>File Type:</dt>
                <dd class="filetype"></dd>
                <dt>Python Version:</dt>
                <dd class="pyversion"></dd>
            </dl>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
            <a href="#" class="btn btn-danger">Delete</a>
        </div>
    </div>
</div>
{% endblock %}