yolapi/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

from pypi.views import index
from sync.views import sync

urlpatterns = [
    path('', index, name='index'),
    path('pypi/', include(('pypi.urls', 'pypi'), namespace='pypi')),
    path(
        'simple/',
        include(('pypi.simple.urls', 'pypi'), namespace='simple')
    ),

    path(
        'importer/',
        include(('importer.urls', 'importer'), namespace='importer')
    ),
    path('sync/', sync, name='sync'),

    path(
        'robots.txt',
        TemplateView.as_view(
            template_name='robots.txt', content_type='text/plain'
        )
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yolapi/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.generic.simple import direct_to_template


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'yolapi.pypi.views.index', name='index'),
    url(r'^pypi/', include('yolapi.pypi.urls')),
    url(r'^simple/', include('yolapi.pypi.simple.urls')),

    url(r'^importer/', include('yolapi.importer.urls')),
    url(r'^sync/$', 'yolapi.sync.views.sync'),

    url(r'^robots.txt$', direct_to_template,
        {'template': 'robots.txt', 'mimetype': 'text/plain'}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

yolapi/templates/base.html
<!DOCTYPE html>{% load static %}
<html>
    <head>
        <title>
            {% block title %}{{ title }}{% endblock %}
        </title>
        <link href="{% static 'css/yolapi.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap.min.css" integrity="sha512-dhpxh4AzF050JM736FF+lLVybu28koEYRrSJtTKfA4Z7jKXJNQ5LcxKmHEwruFN2DuOAi9xeKROJ4Z+sttMjqw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="{% static 'css/pygments.css' %}" rel="stylesheet">
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        <div class="navbar navbar-static-top">
            <div class="navbar-inner">
                <a class="brand" href="/">YolaPI</a>
                <ul class="nav">
                    {% block nav %}
                    {% endblock %}
                </ul>
                <ul class="nav pull-right">
                    <li><a class="post" data-url="{% url 'sync' %}"
                           data-started="Requesting Sync..." href="#">Sync</a></li>
                    <li><a href="{% url 'importer:index' %}">Import</a></li>
                </ul>
            </div>
        </div>
        {% block content %}
        {% endblock %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/js/bootstrap.min.js" integrity="sha512-28e47INXBDaAH0F91T8tup57lcH+iIqq9Fefp6/p+6cgF7RKnqIMSmZqZKceq7WWo9upYMBLMYyMsFq7zHGlug==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="{% static 'js/yolapi.js' %}"></script>
    </body>
</html>